### ISSUE TITLE
More customization

### ISSUE THREAD

**Issue by alejandrogiubel** [AbduzZami/open_street_map_search_and_pick#2]
Hi great lib. More customization will be nice, like, change icons, hint text, button style, decoration for the input, change de marker. Thanks

**Comment by AbduzZami** [comment]
Thank you @alejandrogiubel for your suggestion. Yeah I should have done that. I will in the next update in Sha Allah.

**Comment by ZdenekKrcal** [comment]
any updates here?

**Comment by AbduzZami** [comment]
@ZdenekKrcal yeah few of them are implemented. Sorry I didn't get time to do all of them.

**Comment by AbduzZami** [comment]
You can also contribute to the project. I will surely show your name in the pub.dev then.

**Comment by AbduzZami** [comment]
your pull request was added

**Comment by AbduzZami** [comment]
Your name will be in the pubdev from the next update
