### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED: certificate has expired

### ISSUE THREAD

**Issue by BasheerShamar** [AbduzZami/open_street_map_search_and_pick#3]
I got this error when starting the app:

 [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error: 
 	CERTIFICATE_VERIFY_FAILED: certificate has expired(handshake.cc:393))
 #0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99:46)
 #1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:142:25)
 #2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:911:54)
 #3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1040:19)
<asynchronous suspension>

**Comment by AbduzZami** [comment]
I think this error is not for this package
