### ISSUE TITLE
Map is not working

### ISSUE THREAD

**Issue by Si11-ibrahim** [AbduzZami/open_street_map_search_and_pick#33]
I followed the documentation in the pub.dev but the map is not showing and it says **something went wrong**. How can i resolve this problem? Should i have to do furthermore setups?
![Screenshot 2024-09-09 235629](https://github.com/user-attachments/assets/1dbdf0a7-708f-4fd1-ad7e-95b90a2a9a3d)

**Comment by rhogan73** [comment]
I had the same problem, and went and debugged the code.  The newest version is trying to use Location Services on the device, which means if you haven't configured the perms in your Info.plist or the AndroidManifest.xml, it quietly errors out.  To get the services working grant the permissions, and when you restart your application you should see it requests perms and then runs successfully

**Comment by Si11-ibrahim** [comment]
It didn't work. I created the picker using flutter_map, latlong2 and geocoding packages. Thanks for your reply.
