### ISSUE TITLE
How to get the state name from the address ? 

### ISSUE THREAD

**Issue by Peteritor** [AbduzZami/open_street_map_search_and_pick#8]
It's amazing work you guys have done. How can I get only the state name for example get 'Texas' out of the entire address of the location. Is there any built in function to do so ? 

Thanks

**Comment by AbduzZami** [comment]
Sorry it was not added in the package to keep it simple. But I think it should be added to the package, I ll add that in the next update in sha Allah. You can also do it by yourself and if you send a pull request I will add it to the package. And your github profile will also be listed in the contributors section in pub.dev.
